name: Install Playit

on:
  workflow_dispatch:

jobs:
  install-playit:
    runs-on: ubuntu-24.04
    steps:
      - name: Add playit GPG key
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
      - name: Install playit
        run: |
          sudo apt update
          sudo apt install -y playit
      - name: Claim with token and start
        run: |
          sudo usermod -aG playit $USER
          sg playit -c "playit claim secret 1b8d63caf9315b6bbefdbefc5419c64c4f38cf5c896c86b9b6268a7f6eb580c4"
          sudo systemctl restart playit
          sleep 2
          sudo playit status
